### ISSUE TITLE
Which Linux capabilities are required to properly function?

### ISSUE THREAD

**Issue by juniorz** [Yelp/dumb-init#284]
It would be great to have documented in the README which [Linux capabilities](https://man7.org/linux/man-pages/man7/capabilities.7.html) are required by `dumb-init` in order to function properly.

We often see tools in the Kubernetes ecosystem being obsessed with dropping all capabilities via

```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
```

and then operators learn the container uses `dumb-init` as PID1 when they notice the [termination of pods](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) is broken because `dumb-init` is unable to terminate all children processes.
